language: ruby
sudo: false
cache: bundler
dist: trusty

# Early warning system to catch if Rubygems breaks something
before_install:
  - gem update --system $(grep rubygems omnibus_overrides.rb | cut -d'"' -f2)
  - gem --version
  - rm -f .bundle/config

bundler_args: --without changelog docgen guard maintenance omnibus_package tools aix bsd mac_os_x solaris windows --frozen

env:
  global:
    - FORCE_FFI_YAJL=ext

matrix:
  include:
    - rvm: 2.4.3
      env:
        RSPEC: 1
      script: $(which bundle) exec rspec
    - rvm: 2.4.3
      env:
        CHEFSTYLE: 1
      script: $(which bundle) exec rake style:chefstyle
    - rvm: 2.4.3
      env:
        COOKSTYLE: 1
      script: $(which bundle) exec rake style:cookstyle
    - rvm: 2.4.3
      env:
        FOODCRITIC: 1
      script: $(which bundle) exec rake style:foodcritic

branches:
  only:
    - master
