language: ruby
cache: bundler
dist: xenial

addons:
  apt:
    packages:
      - libarchive-dev

# Early warning system to catch if Rubygems breaks something
before_install:
  - gem update --system $(grep rubygems omnibus_overrides.rb | cut -d'"' -f2)
  - gem install bundler --version $(grep bundler omnibus_overrides.rb | cut -d'"' -f2) # https://github.com/travis-ci/travis-ci/issues/8969
  - gem --version
  - rm -f .bundle/config

bundler_args: --without omnibus_package tools aix bsd mac_os_x solaris windows --frozen

env:
  global:
    - FORCE_FFI_YAJL=ext

matrix:
  include:
    - rvm: 2.4.6
      env:
        RSPEC: 1
      script: bundle exec rspec
    - rvm: 2.5.5
      env:
        RSPEC: 1
      script: bundle exec rspec
    - rvm: 2.5.5
      env:
        CHEFSTYLE: 1
      script: bundle exec rake style:chefstyle
    - rvm: 2.5.5
      env:
        COOKSTYLE: 1
      script: bundle exec rake style:cookstyle
    - rvm: 2.5.5
      env:
        FOODCRITIC: 1
      script: bundle exec rake style:foodcritic

branches:
  only:
    - master
    - chefdk-3
