version: 1

update_configs:
  - package_manager: "ruby:bundler"
    directory: "/omnibus"
    update_schedule: "live"
    default_labels:
      - "Type: Chore"
    ignored_updates:
      - match:
        dependency_name: "aws*"